/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package polije.ppl.tailor.view.util;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import polije.ppl.tailor.view.LoginView;

import polije.ppl.tailor.view.admin.*;

/**
 *
 * @author ibad
 */
public class SidebarAdminView extends javax.swing.JPanel {
    private JFrame parent;

    /**
     * Creates new form SidebarView
     * @param <T>
     * @param parent
     */
    public <T extends JFrame> SidebarAdminView(T parent) {
        this.parent = parent;
        initComponents();
        activeState();
    }

    private void activeState() {
        int parentCode = parent.getClass().hashCode();
        int dashCode = DashboardAdminView.class.hashCode();
        int transCode = DataTransaksiView.class.hashCode();
        int custCode = DataPelangganView.class.hashCode();
        int packCode = DataPaketView.class.hashCode();
        int tailCode = DataPenjahitView.class.hashCode();
        int pandCode = PanduanAdminView.class.hashCode();
        int lapCode = LaporanAdminView.class.hashCode();

        if(parentCode == dashCode) dashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sidebarbdn/Sidebar DashBoard.png")));
        if(parentCode == transCode) transactionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sidebarbdn/Sidebar Transaksi.png")));
        if(parentCode == custCode) customerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sidebarbdn/Sidebar Pelanggan.png")));
        if(parentCode == packCode) packageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sidebarbdn/Sidebar Paket.png")));
        if(parentCode == tailCode) tailorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sidebarbdn/Sidebar Penjahit.png")));
        if(parentCode == pandCode) panduanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sidebarbdn/Panduan.png")));
        if(parentCode == lapCode) laporanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sidebarbdn/Laporan.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardBtn = new javax.swing.JLabel();
        packageBtn = new javax.swing.JLabel();
        customerBtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        transactionBtn = new javax.swing.JLabel();
        tailorBtn = new javax.swing.JLabel();
        panduanBtn = new javax.swing.JLabel();
        laporanBtn = new javax.swing.JLabel();
        sidebarImg = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(277, 708));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(277, 708));
        setLayout(null);

        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
        });
        add(dashboardBtn);
        dashboardBtn.setBounds(38, 104, 199, 49);

        packageBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                packageBtnMouseClicked(evt);
            }
        });
        add(packageBtn);
        packageBtn.setBounds(38, 175, 199, 49);

        customerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerBtnMouseClicked(evt);
            }
        });
        add(customerBtn);
        customerBtn.setBounds(38, 245, 199, 49);

        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        add(logoutBtn);
        logoutBtn.setBounds(40, 596, 200, 50);

        transactionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionBtnMouseClicked(evt);
            }
        });
        add(transactionBtn);
        transactionBtn.setBounds(38, 315, 199, 49);

        tailorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tailorBtnMouseClicked(evt);
            }
        });
        add(tailorBtn);
        tailorBtn.setBounds(38, 385, 199, 49);

        panduanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panduanBtnMouseClicked(evt);
            }
        });
        add(panduanBtn);
        panduanBtn.setBounds(38, 527, 200, 50);

        laporanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanBtnMouseClicked(evt);
            }
        });
        add(laporanBtn);
        laporanBtn.setBounds(38, 456, 200, 50);

        sidebarImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Sidebar Admin.png"))); // NOI18N
        add(sidebarImg);
        sidebarImg.setBounds(0, 0, 277, 708);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        new LoginView().setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
        new DashboardAdminView().setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_dashboardBtnMouseClicked

    private void packageBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packageBtnMouseClicked
        new DataPaketView().setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_packageBtnMouseClicked

    private void customerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerBtnMouseClicked
        new DataPelangganView().setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_customerBtnMouseClicked

    private void transactionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionBtnMouseClicked
        new DataTransaksiView().setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_transactionBtnMouseClicked

    private void tailorBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tailorBtnMouseClicked
        new DataPenjahitView().setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_tailorBtnMouseClicked

    private void panduanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panduanBtnMouseClicked
        new PanduanAdminView().setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_panduanBtnMouseClicked

    private void laporanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanBtnMouseClicked
        new LaporanAdminView().setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_laporanBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerBtn;
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JLabel laporanBtn;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel packageBtn;
    private javax.swing.JLabel panduanBtn;
    private javax.swing.JLabel sidebarImg;
    private javax.swing.JLabel tailorBtn;
    private javax.swing.JLabel transactionBtn;
    // End of variables declaration//GEN-END:variables
}
