/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package polije.ppl.tailor.view.util;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import polije.ppl.tailor.view.LoginView;

/**
 *
 * @author ibad
 */
public class SidebarTailorView extends javax.swing.JPanel {
    private JFrame parent;
    
    /**
     * Creates new form SidebarView
     */
    public <T extends JFrame> SidebarTailorView(T parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardBtn = new javax.swing.JLabel();
        transactionBtn = new javax.swing.JLabel();
        measureBtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        sidebarImg = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(277, 708));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(277, 708));
        setLayout(null);
        add(dashboardBtn);
        dashboardBtn.setBounds(40, 100, 200, 50);
        add(transactionBtn);
        transactionBtn.setBounds(40, 170, 200, 50);
        add(measureBtn);
        measureBtn.setBounds(40, 240, 200, 50);

        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        add(logoutBtn);
        logoutBtn.setBounds(40, 310, 200, 50);

        sidebarImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sidebar-tailor.png"))); // NOI18N
        add(sidebarImg);
        sidebarImg.setBounds(0, 0, 277, 708);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        new LoginView().setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel measureBtn;
    private javax.swing.JLabel sidebarImg;
    private javax.swing.JLabel transactionBtn;
    // End of variables declaration//GEN-END:variables
}
