/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package polije.ppl.tailor.view.util;

import javax.swing.JFrame;
import polije.ppl.tailor.view.LoginView;
import polije.ppl.tailor.view.tailor.DashBoardPenjahitView;
import polije.ppl.tailor.view.tailor.TransaksiPenjahitView;
import polije.ppl.tailor.view.tailor.UkuranView;

/**
 *
 * @author ibad
 */
public class SidebarTailorView extends javax.swing.JPanel {
    private JFrame parent;
    
    /**
     * Creates new form SidebarView
     * @param <T>
     * @param parent
     */
    public <T extends JFrame> SidebarTailorView(T parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardBtn = new javax.swing.JLabel();
        transactionBtn = new javax.swing.JLabel();
        measureBtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        sidebarImg = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(277, 708));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(277, 708));
        setLayout(null);

        dashboardBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hafidz\\OneDrive\\Documents\\NetBeansProjects\\Tailor_TS\\src\\Page\\Sidebar DashBoard.png")); // NOI18N
        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
        });
        add(dashboardBtn);
        dashboardBtn.setBounds(38, 103, 200, 50);

        transactionBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hafidz\\OneDrive\\Documents\\NetBeansProjects\\Tailor_TS\\src\\Page\\Sidebar Transaksi.png")); // NOI18N
        transactionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionBtnMouseClicked(evt);
            }
        });
        add(transactionBtn);
        transactionBtn.setBounds(38, 174, 200, 50);

        measureBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hafidz\\OneDrive\\Documents\\NetBeansProjects\\Tailor_TS\\src\\Page\\Sidebar Ukuran.png")); // NOI18N
        measureBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                measureBtnMouseClicked(evt);
            }
        });
        add(measureBtn);
        measureBtn.setBounds(38, 244, 200, 50);

        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        add(logoutBtn);
        logoutBtn.setBounds(40, 310, 200, 50);

        sidebarImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hafidz\\OneDrive\\Documents\\NetBeansProjects\\Tailor_TS\\src\\Page\\Sidebar Penjahit.png")); // NOI18N
        add(sidebarImg);
        sidebarImg.setBounds(0, 0, 277, 708);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        new LoginView().setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void transactionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionBtnMouseClicked
        new TransaksiPenjahitView().setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_transactionBtnMouseClicked

    private void measureBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_measureBtnMouseClicked
        new UkuranView().setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_measureBtnMouseClicked

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
        // TODO add your handling code here:
        new DashBoardPenjahitView().setVisible(true);
        parent.dispose();
        
        
        
    }//GEN-LAST:event_dashboardBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel measureBtn;
    private javax.swing.JLabel sidebarImg;
    private javax.swing.JLabel transactionBtn;
    // End of variables declaration//GEN-END:variables
}
