/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polije.ppl.tailor.view.tailor;

import java.util.Date;
import polije.ppl.tailor.data.SessionData;
import polije.ppl.tailor.repository.DashboardRepository;
import polije.ppl.tailor.util.NumberUtil;
import polije.ppl.tailor.view.util.SidebarTailorView;

/**
 *
 * @author ibad
 */
public class DashBoardPenjahitView extends javax.swing.JFrame {
    private DashboardRepository repo = new DashboardRepository();

    /**
     * Creates new form DashBoardPenjahitView
     */
    public DashBoardPenjahitView() {
        this.setTitle("DashBoard Penjahit - Tailor TS");
        initComponents();

        sidebar.add(new SidebarTailorView(this));
        sidebar.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        int transaction = repo.getTransactionPerMonth(new Date(), SessionData.account);
        totalTransaction.setText(NumberUtil.formatDec(transaction));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        totalTransaction = new javax.swing.JLabel();
        totalIncome1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1088, 708));
        getContentPane().setLayout(null);

        sidebar.setMaximumSize(new java.awt.Dimension(277, 708));
        sidebar.setMinimumSize(new java.awt.Dimension(277, 708));
        sidebar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        getContentPane().add(sidebar);
        sidebar.setBounds(0, 0, 277, 708);

        totalTransaction.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        totalTransaction.setForeground(new java.awt.Color(118, 159, 205));
        totalTransaction.setText("jLabel2");
        getContentPane().add(totalTransaction);
        totalTransaction.setBounds(372, 247, 130, 18);

        totalIncome1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        totalIncome1.setForeground(new java.awt.Color(0, 0, 0));
        totalIncome1.setText("bulan ini");
        getContentPane().add(totalIncome1);
        totalIncome1.setBounds(440, 267, 130, 15);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/Dashborad Penjahit.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(1089, 740));
        background.setMinimumSize(new java.awt.Dimension(1089, 740));
        background.setPreferredSize(new java.awt.Dimension(1089, 740));
        getContentPane().add(background);
        background.setBounds(-3, -4, 1180, 710);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardPenjahitView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel totalIncome1;
    private javax.swing.JLabel totalTransaction;
    // End of variables declaration//GEN-END:variables
}
