/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polije.ppl.tailor.view.tailor;

import java.awt.Color;
import polije.ppl.tailor.view.util.SidebarTailorView;

/**
 *
 * @author Hafidz
 */
public class EditTransaksiView extends javax.swing.JFrame {

    /**
     * Creates new form EditTransaksiView
     */
    public EditTransaksiView() {
        initComponents();
        namapelanggan.setOpaque(false);
        namapelanggan.setBackground(new java.awt.Color(255, 255, 255, 0));

        status.setOpaque(false);
        status.setBackground(new java.awt.Color(255, 255, 255, 0));

        tglambil.setOpaque(false);
        tglambil.setBackground(new java.awt.Color(255, 255, 255, 0));

        totalharga.setOpaque(false);
        totalharga.setBackground(new java.awt.Color(255, 255, 255, 0));

        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(null);

        catatan.setBorder(null);
        catatan.setBackground(new Color(0,0,0,0));
        
        sidebar.add(new SidebarTailorView(this));
        sidebar.setBackground(new java.awt.Color(255, 255, 255, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        namapelanggan = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        tglambil = new javax.swing.JTextField();
        totalharga = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        catatan = new javax.swing.JTextArea();
        bbutton = new javax.swing.JLabel();
        simpan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pensanan = new javax.swing.JTable();
        imginti = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1089, 740));
        setPreferredSize(new java.awt.Dimension(1089, 740));
        getContentPane().setLayout(null);

        sidebar.setMaximumSize(new java.awt.Dimension(277, 708));
        sidebar.setMinimumSize(new java.awt.Dimension(277, 708));
        sidebar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        getContentPane().add(sidebar);
        sidebar.setBounds(0, 0, 277, 708);

        namapelanggan.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        namapelanggan.setBorder(null);
        namapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapelangganActionPerformed(evt);
            }
        });
        getContentPane().add(namapelanggan);
        namapelanggan.setBounds(400, 140, 500, 30);

        status.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        status.setBorder(null);
        getContentPane().add(status);
        status.setBounds(400, 210, 240, 30);

        tglambil.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tglambil.setBorder(null);
        getContentPane().add(tglambil);
        tglambil.setBounds(662, 210, 240, 30);

        totalharga.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        totalharga.setBorder(null);
        totalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalhargaActionPerformed(evt);
            }
        });
        getContentPane().add(totalharga);
        totalharga.setBounds(717, 380, 180, 30);

        jScrollPane2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        catatan.setColumns(20);
        catatan.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        catatan.setRows(5);
        jScrollPane2.setViewportView(catatan);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(400, 440, 500, 130);

        bbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbuttonMouseClicked(evt);
            }
        });
        getContentPane().add(bbutton);
        bbutton.setBounds(383, 71, 40, 30);

        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(824, 592, 90, 30);

        pensanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(pensanan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(390, 280, 510, 80);

        imginti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/tailor-edittrans.png"))); // NOI18N
        getContentPane().add(imginti);
        imginti.setBounds(0, 0, 1089, 708);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapelangganActionPerformed

    private void totalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalhargaActionPerformed

    private void bbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bbuttonMouseClicked

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTransaksiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bbutton;
    private javax.swing.JTextArea catatan;
    private javax.swing.JLabel imginti;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField namapelanggan;
    private javax.swing.JTable pensanan;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel simpan;
    private javax.swing.JTextField status;
    private javax.swing.JTextField tglambil;
    private javax.swing.JTextField totalharga;
    // End of variables declaration//GEN-END:variables
}
