/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polije.ppl.tailor.view.tailor;

import java.util.HashMap;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import polije.ppl.tailor.data.SessionData;
import polije.ppl.tailor.entity.Transaction;
import polije.ppl.tailor.repository.TransactionRepository;
import polije.ppl.tailor.util.NumberUtil;
import polije.ppl.tailor.util.ViewUtil;
import polije.ppl.tailor.view.util.SidebarTailorView;

/**
 *
 * @author Hafidz
 */
public class TransaksiPenjahitView extends javax.swing.JFrame {
    private TransactionRepository transRepo = new TransactionRepository();

    /**
     * Creates new form TransaksiPenjahit
     */
    public TransaksiPenjahitView() {
        this.setTitle("Transaksi Penjahit - Tailor TS");
        initComponents();

        search.setOpaque(false);
        search.setBackground(new java.awt.Color(255, 255, 255, 0));

        sidebar.add(new SidebarTailorView(this));
        sidebar.setBackground(new java.awt.Color(255, 255, 255, 0));

        loadTable(transRepo.get(
            new HashMap<>() {{
                put("account_id", SessionData.account.getId());
            }}
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1089, 740));
        setPreferredSize(new java.awt.Dimension(1089, 740));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);

            }
        });

        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(362, 260, 640, 402);

        search.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(780, 203, 180, 30);

        sidebar.setMaximumSize(new java.awt.Dimension(277, 708));
        sidebar.setMinimumSize(new java.awt.Dimension(277, 708));
        sidebar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        getContentPane().add(sidebar);
        sidebar.setBounds(0, 0, 277, 708);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/tailor-transactions.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, 0, 1080, 710);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchActionPerformed
        List<Transaction> transactions = transRepo.searchByAccount(
            SessionData.account,
            new HashMap<>() {{
                put("total", search.getText());
                put("status", search.getText());
            }}
        );

        loadTable(transactions);
    }//GEN-LAST:event_searchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_datapaketMouseClicked
        int row = jTable1.getSelectedRow();
        String value = jTable1.getModel().getValueAt(row, 5).toString();
        Transaction trans = transRepo.get(Integer.valueOf(value));

        new EditTransaksiView(trans).setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPenjahitView().setVisible(true);
            }
        });
    }

    private void loadTable(List<Transaction> transactions) {
        int no = 1;
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("No");
        model.addColumn("Tanggal Transaksi");
        model.addColumn("Tanggal Ambil");
        model.addColumn("Status");
        model.addColumn("Total");
        model.addColumn("ID");

        for(Transaction transaction: transactions) {
            model.addRow(new Object[] {
                no++,
                transaction.getDate().toString(),
                transaction.getDueDate()== null ? "-": transaction.getDueDate().toString(),
                transaction.getStatus().toString(),
                NumberUtil.formatDec(transaction.getTotal()),
                transaction.getId()
            });
        }

        jTable1.setModel(model);
        ViewUtil.hideTableColumn(jTable1, 5);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField search;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
