/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polije.ppl.tailor.view;

import javax.swing.JOptionPane;
import polije.ppl.tailor.service.AuthService;

/**
 *
 * @author ibad
 */
public class LupaPasswordView extends javax.swing.JFrame {

    /**
     * Creates new form LupaPasswordView
     */
    public LupaPasswordView() {
        initComponents();
        initTransparents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        submitBtn = new javax.swing.JLabel();
        backBtn = new javax.swing.JLabel();
        page = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1088, 708));
        setPreferredSize(new java.awt.Dimension(1088, 708));
        getContentPane().setLayout(null);

        usernameInput.setFont(new java.awt.Font("Ubuntu Medium", 0, 20)); // NOI18N
        usernameInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usernameInput.setMinimumSize(new java.awt.Dimension(1088, 708));
        usernameInput.setPreferredSize(new java.awt.Dimension(1088, 708));
        getContentPane().add(usernameInput);
        usernameInput.setBounds(400, 342, 290, 33);

        emailInput.setFont(new java.awt.Font("Ubuntu Medium", 0, 20)); // NOI18N
        emailInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        emailInput.setMinimumSize(new java.awt.Dimension(1088, 708));
        emailInput.setPreferredSize(new java.awt.Dimension(1088, 708));
        getContentPane().add(emailInput);
        emailInput.setBounds(400, 419, 290, 33);

        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });
        getContentPane().add(submitBtn);
        submitBtn.setBounds(380, 470, 330, 40);

        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(360, 180, 40, 30);

        page.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/Lupa Password.png"))); // NOI18N
        getContentPane().add(page);
        page.setBounds(0, 0, 1089, 708);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
        if(new AuthService().forgotPassword(usernameInput.getText(), emailInput.getText())) {
            new InputKodeView().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Data akun tidak ditemukan");
        }
    }//GEN-LAST:event_submitBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        new LoginView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LupaPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LupaPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LupaPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LupaPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LupaPasswordView().setVisible(true);
            }
        });
    }

    private void initTransparents() {
        usernameInput.setOpaque(false);
        usernameInput.setBackground(new java.awt.Color(255, 255, 255, 0));

        emailInput.setOpaque(false);
        emailInput.setBackground(new java.awt.Color(255, 255, 255, 0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtn;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel page;
    private javax.swing.JLabel submitBtn;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
