/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polije.ppl.tailor.view;

import java.util.HashMap;

import javax.swing.JOptionPane;

import polije.ppl.tailor.entity.Account;
import polije.ppl.tailor.repository.AccountRepository;
import polije.ppl.tailor.service.AuthService;

/**
 *
 * @author Hafidz
 */
public class LupaPassView extends javax.swing.JFrame {
    private AccountRepository accRepo;

    /**
     * Creates new form LupaPassView
     */
    public LupaPassView() {
        accRepo = new AccountRepository();

        initComponents();
        usename.setOpaque(false);
        usename.setBackground(new java.awt.Color(255, 255, 255, 0));

        email.setOpaque(false);
        email.setBackground(new java.awt.Color(255, 255, 255, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bbutton = new javax.swing.JLabel();
        usename = new javax.swing.JTextField();
        kirim = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        IMGinti = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1088, 708));
        getContentPane().setLayout(null);

        bbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbuttonMouseClicked(evt);
            }
        });
        getContentPane().add(bbutton);
        bbutton.setBounds(358, 178, 40, 30);

        usename.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        usename.setBorder(null);
        usename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usenameActionPerformed(evt);
            }
        });
        getContentPane().add(usename);
        usename.setBounds(390, 336, 310, 40);

        kirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kirimMouseClicked(evt);
            }
        });
        getContentPane().add(kirim);
        kirim.setBounds(383, 469, 320, 40);

        email.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        email.setBorder(null);
        getContentPane().add(email);
        email.setBounds(390, 413, 310, 40);

        IMGinti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/Lupa Password.png"))); // NOI18N
        IMGinti.setMaximumSize(new java.awt.Dimension(1088, 708));
        IMGinti.setMinimumSize(new java.awt.Dimension(1088, 708));
        IMGinti.setPreferredSize(new java.awt.Dimension(1088, 708));
        getContentPane().add(IMGinti);
        IMGinti.setBounds(0, 0, 1088, 708);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbuttonMouseClicked
        new LoginView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bbuttonMouseClicked

    private void usenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usenameActionPerformed

    private void kirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kirimMouseClicked
        if(new AuthService().forgotPassword(usename.getText(), email.getText())) {
            new InputKodeView().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Data akun tidak ditemukan");
        }

    }//GEN-LAST:event_kirimMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LupaPassView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LupaPassView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LupaPassView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LupaPassView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LupaPassView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMGinti;
    private javax.swing.JLabel bbutton;
    private javax.swing.JTextField email;
    private javax.swing.JLabel kirim;
    private javax.swing.JTextField usename;
    // End of variables declaration//GEN-END:variables
}
