/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polije.ppl.tailor.view.admin;

import java.awt.Color;
import java.util.Date;
import java.util.List;

import polije.ppl.tailor.data.ChartData;
import polije.ppl.tailor.repository.DashboardRepository;
import polije.ppl.tailor.util.NumberUtil;
import polije.ppl.tailor.view.util.SidebarAdminView;
import raven.chart.ModelChart;

/**
 *
 * @author ibad
 */
public class DashboardAdminView extends javax.swing.JFrame {
    private DashboardRepository repo = new DashboardRepository();

    /**
     * Creates new form DashboardAdminView
     */
    public DashboardAdminView() {
        this.setTitle("DashBoard Admin - Tailor TS");
        initComponents();
        initChart();

        sidebar.add(new SidebarAdminView(this));
        sidebar.setBackground(new java.awt.Color(255, 255, 255, 0));

        totalIncome.setText(NumberUtil.formatDec(repo.getIncomePerMonth(new Date())));
        totalCustomer.setText(NumberUtil.formatDec(repo.getCustomerTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        chart = new raven.chart.CurveLineChart();
        totalIncome = new javax.swing.JLabel();
        totalIncome1 = new javax.swing.JLabel();
        totalCustomer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1089, 708));
        getContentPane().setLayout(null);

        sidebar.setMinimumSize(new java.awt.Dimension(277, 708));
        sidebar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        getContentPane().add(sidebar);
        sidebar.setBounds(0, 0, 277, 708);

        chart.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        chart.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(chart);
        chart.setBounds(390, 360, 530, 290);

        totalIncome.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        totalIncome.setForeground(new java.awt.Color(118, 159, 205));
        totalIncome.setText("jLabel2");
        getContentPane().add(totalIncome);
        totalIncome.setBounds(372, 247, 130, 18);

        totalIncome1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        totalIncome1.setForeground(new java.awt.Color(0, 0, 0));
        totalIncome1.setText("bulan ini");
        getContentPane().add(totalIncome1);
        totalIncome1.setBounds(440, 267, 130, 15);

        totalCustomer.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        totalCustomer.setForeground(new java.awt.Color(118, 159, 205));
        totalCustomer.setText("jLabel2");
        getContentPane().add(totalCustomer);
        totalCustomer.setBounds(565, 247, 130, 18);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/Dashbord Admin.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1089, 708);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void initChart() {
        List<ChartData> cData = repo.getChartStats();

        chart.addLegend("Pendapatan", Color.decode("#8360c3"), Color.decode("#2ebf91"));
        chart.addLegend("Transaksi", Color.decode("#B279A7"), Color.decode("#D387AB"));

        for(ChartData data: cData) {
            chart.addData(new ModelChart(data.getMonth(), new double[] {
                data.getAmount(),
                data.getTransactions()
            }));
        }

        if(cData.size() > 1) chart.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.chart.CurveLineChart chart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel totalCustomer;
    private javax.swing.JLabel totalIncome;
    private javax.swing.JLabel totalIncome1;
    // End of variables declaration//GEN-END:variables
}
