/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polije.ppl.tailor.view.admin;

import polije.ppl.tailor.view.util.SidebarAdminView;

/**
 *
 * @author Hafidz
 */
public class EditDataPenjahitView extends javax.swing.JFrame {

    /**
     * Creates new form EditDataPenjahitView
     */
    public EditDataPenjahitView() {
        initComponents();
        
        sidebar.add(new SidebarAdminView(this));
        sidebar.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        namapenjahit.setOpaque(false);
        namapenjahit.setBackground(new java.awt.Color(255, 255, 255, 0));

        username.setOpaque(false);
        username.setBackground(new java.awt.Color(255, 255, 255, 0));

        email.setOpaque(false);
        email.setBackground(new java.awt.Color(255, 255, 255, 0));

        password.setOpaque(false);
        password.setBackground(new java.awt.Color(255, 255, 255, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        backbtn = new javax.swing.JLabel();
        namapenjahit = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        btn_hapus = new javax.swing.JLabel();
        simpan = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1089, 708));
        getContentPane().setLayout(null);

        sidebar.setMinimumSize(new java.awt.Dimension(277, 708));
        sidebar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        getContentPane().add(sidebar);
        sidebar.setBounds(0, 0, 277, 708);

        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        getContentPane().add(backbtn);
        backbtn.setBounds(376, 196, 40, 30);

        namapenjahit.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        namapenjahit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        namapenjahit.setBorder(null);
        getContentPane().add(namapenjahit);
        namapenjahit.setBounds(397, 260, 500, 40);

        username.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        username.setBorder(null);
        getContentPane().add(username);
        username.setBounds(397, 332, 230, 40);

        email.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        email.setBorder(null);
        getContentPane().add(email);
        email.setBounds(660, 330, 240, 40);

        password.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        password.setBorder(null);
        getContentPane().add(password);
        password.setBounds(397, 402, 500, 40);

        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(390, 460, 80, 30);

        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(817, 460, 90, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/Edit Data Penjahit.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1089, 708);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        new DataPenjahitView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
       
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        
    }//GEN-LAST:event_simpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDataPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDataPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDataPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDataPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDataPenjahitView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JTextField email;
    private javax.swing.JTextField namapenjahit;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel simpan;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
