/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polije.ppl.tailor.view.admin;

import java.util.Set;

import javax.swing.JOptionPane;

import jakarta.validation.ConstraintViolation;
import polije.ppl.tailor.entity.Package;
import polije.ppl.tailor.repository.PackageRepository;
import polije.ppl.tailor.repository.Repository;
import polije.ppl.tailor.util.ValidationUtil;
import polije.ppl.tailor.view.util.SidebarAdminView;

/**
 *
 * @author Hafidz
 */
public class EditDataPaketView extends javax.swing.JFrame {
    private Package pkg;
    private Repository<Package> pkgRepo = new PackageRepository();

    /**
     * Creates new form EditDataPaketView
     */
    public EditDataPaketView(Package pkg) {
        this.pkg = pkg;

        initComponents();
        fillForm();

        sidebar.add(new SidebarAdminView(this));
        sidebar.setBackground(new java.awt.Color(255, 255, 255, 0));

        tipe_pakaian.setOpaque(false);
        tipe_pakaian.setBackground(new java.awt.Color(255, 255, 255, 0));

        harga.setOpaque(false);
        harga.setBackground(new java.awt.Color(255, 255, 255, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        tipe_pakaian = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        bbtn = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1088, 740));
        getContentPane().setLayout(null);

        sidebar.setMinimumSize(new java.awt.Dimension(277, 708));
        sidebar.setPreferredSize(new java.awt.Dimension(1089, 708));
        sidebar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        getContentPane().add(sidebar);
        sidebar.setBounds(0, 0, 277, 708);

        tipe_pakaian.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        tipe_pakaian.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tipe_pakaian.setBorder(null);
        getContentPane().add(tipe_pakaian);
        tipe_pakaian.setBounds(410, 220, 490, 40);

        harga.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        harga.setBorder(null);
        getContentPane().add(harga);
        harga.setBounds(410, 280, 490, 40);

        bbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbtnMouseClicked(evt);
            }
        });
        getContentPane().add(bbtn);
        bbtn.setBounds(385, 153, 40, 40);

        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(392, 339, 90, 30);

        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan);
        btn_simpan.setBounds(825, 339, 90, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/Edit Data Paket.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1088, 708);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbtnMouseClicked
        new DataPaketView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bbtnMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        int clicked = JOptionPane.showConfirmDialog(this, "Apakah anda yakin?");

        if(clicked == 0) {
            pkgRepo.delete(pkg.getId());

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
            new DataPaketView().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        String hargaVal = harga.getText();

        pkg.setName(tipe_pakaian.getText());
        pkg.setPrice(hargaVal.isBlank() ? 0 : Integer.parseInt(hargaVal));

        Set<ConstraintViolation<Package>> vols = ValidationUtil.validate(pkg);

        if(vols.size() > 0) {
            JOptionPane.showMessageDialog(this, ValidationUtil.getErrorsAsString(vols, "\n"));
            return;
        }

        pkgRepo.update(pkg);

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
        new DataPaketView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_simpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDataPaketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDataPaketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDataPaketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDataPaketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    private void fillForm() {
        tipe_pakaian.setText(pkg.getName());
        harga.setText(String.valueOf(pkg.getPrice()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bbtn;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JTextField harga;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTextField tipe_pakaian;
    // End of variables declaration//GEN-END:variables
}
