/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polije.ppl.tailor.view.admin;

import java.util.Date;

import javax.swing.table.DefaultTableModel;

import polije.ppl.tailor.data.MostItemData;
import polije.ppl.tailor.data.TransactionStatus;
import polije.ppl.tailor.entity.Transaction;
import polije.ppl.tailor.service.ReportService;
import polije.ppl.tailor.util.NumberUtil;
import polije.ppl.tailor.view.util.SidebarAdminView;

/**
 *
 * @author Hafidz
 */
public class LaporanAdminView extends javax.swing.JFrame {
    /**
     * Creates new form LaporanAdminView
     */
    public LaporanAdminView() {
        this.setTitle("Laporan Admin - Tailor TS");
        initComponents();
        initTransparents();

        sidebar.add(new SidebarAdminView(this));
        sidebar.setBackground(new java.awt.Color(255, 255, 255, 0));
        startDate.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mostItems = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        EksporData = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        startDate = new com.toedter.calendar.JDateChooser();
        endDate = new com.toedter.calendar.JDateChooser();
        status = new javax.swing.JComboBox<>();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1089, 708));
        setResizable(false);
        getContentPane().setLayout(null);

        sidebar.setMinimumSize(new java.awt.Dimension(277, 708));
        sidebar.setPreferredSize(new java.awt.Dimension(1089, 708));
        sidebar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        getContentPane().add(sidebar);
        sidebar.setBounds(0, 0, 277, 708);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(361, 230, 570, 330);

        EksporData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EksporDataMouseClicked(evt);
            }
        });
        getContentPane().add(EksporData);
        EksporData.setBounds(800, 106, 130, 40);

        total.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        total.setBorder(null);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total);
        total.setBounds(780, 590, 130, 30);

        startDate.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        startDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                startDatePropertyChange(evt);
            }
        });
        getContentPane().add(startDate);
        startDate.setBounds(410, 177, 155, 30);

        endDate.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        endDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                endDatePropertyChange(evt);
            }
        });
        getContentPane().add(endDate);
        endDate.setBounds(755, 177, 155, 30);

        status.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(
            new Object[] {
                null, TransactionStatus.finish, TransactionStatus.unfinish
            }
        ));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusPropertyChange(evt);
            }
        });
        getContentPane().add(status);
        status.setBounds(615, 180, 90, 24);

        mostItems.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        mostItems.setForeground(new java.awt.Color(118, 159, 205));
        mostItems.setText("jLabel1");
        getContentPane().add(mostItems);
        mostItems.setBounds(490, 596, 200, 19);

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/Laporan.png"))); // NOI18N
        getContentPane().add(BackGround);
        BackGround.setBounds(0, 0, 1088, 708);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initTransparents() {
        total.setOpaque(false);
        total.setBackground(new java.awt.Color(255, 255, 255, 0));

        startDate.setOpaque(false);
        startDate.setBackground(new java.awt.Color(255, 255, 255, 0));

        endDate.setOpaque(false);
        endDate.setBackground(new java.awt.Color(255, 255, 255, 0));
    }

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed

    }//GEN-LAST:event_totalActionPerformed

    private void startDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_startDatePropertyChange
        loadTable();
    }//GEN-LAST:event_startDatePropertyChange

    private void statusPropertyChange(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusPropertyChange
        loadTable();
    }//GEN-LAST:event_statusPropertyChange

    private void endDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_endDatePropertyChange
        loadTable();
    }//GEN-LAST:event_endDatePropertyChange

    private void EksporDataMouseClicked(java.awt.event.MouseEvent evt) {
        ReportService service = new ReportService(
            startDate.getDate(),
            endDate.getDate(),
            (TransactionStatus) status.getSelectedItem()
        );

        service.generate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanAdminView().setVisible(true);
            }
        });
    }

    private void loadTable() {
        ReportService service = new ReportService(
            startDate.getDate(),
            endDate.getDate(),
            (TransactionStatus) status.getSelectedItem()
        );

        int no = 1;
        int grandtotal = 0;
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("No");
        model.addColumn("Tanggal");
        model.addColumn("Pelanggan");
        model.addColumn("Status");
        model.addColumn("Total");

        for(Transaction transaction: service.getData()) {
            model.addRow(new Object[] {
                no++,
                transaction.getDate().toString(),
                transaction.getCustomer().getFullname(),
                transaction.getStatus().toString(),
                NumberUtil.formatDec(transaction.getTotal()),
            });
            grandtotal += transaction.getTotal();
        }

        jTable1.setModel(model);
        total.setText(NumberUtil.formatDec(grandtotal));

        printMostItems();
    }

    private void printMostItems() {
        StringBuilder most = new StringBuilder();
        ReportService service = new ReportService(
            startDate.getDate(),
            endDate.getDate(),
            (TransactionStatus) status.getSelectedItem()
        );

        MostItemData data = service.getMostItems();
        most.append(data.getNames());
        if(data.getQty() > 1) most.append(" (" + data.getQty() + ")");

        mostItems.setText(most.toString());
    }

    private javax.swing.JLabel mostItems;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel EksporData;
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel sidebar;
    private com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JComboBox<Object> status;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
