/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polije.ppl.tailor.view.admin;

import jakarta.validation.ConstraintViolation;
import java.util.Set;
import javax.swing.JOptionPane;

import polije.ppl.tailor.entity.Package;
import polije.ppl.tailor.repository.PackageRepository;
import polije.ppl.tailor.repository.Repository;
import polije.ppl.tailor.util.ValidationUtil;
import polije.ppl.tailor.view.util.SidebarAdminView;

/**
 *
 * @author muhai
 */
public class TambahDataPaketView extends javax.swing.JFrame {
    private Repository<Package> pkgRepo = new PackageRepository();

    /**
     * Creates new form TambahDataPaketView
     */
    public TambahDataPaketView() {
        initComponents();
        
        sidebar.add(new SidebarAdminView(this));
        sidebar.setBackground(new java.awt.Color(255, 255, 255, 0));

        txt_name.setOpaque(false);
        txt_name.setBackground(new java.awt.Color(255, 255, 255, 0));

        txt_price.setOpaque(false);
        txt_price.setBackground(new java.awt.Color(255, 255, 255, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_price = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JLabel();
        btn_reset = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1088, 708));
        getContentPane().setLayout(null);

        txt_price.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        txt_price.setBorder(null);
        getContentPane().add(txt_price);
        txt_price.setBounds(410, 280, 490, 40);

        txt_name.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        txt_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_name.setBorder(null);
        getContentPane().add(txt_name);
        txt_name.setBounds(410, 220, 490, 40);

        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan);
        btn_simpan.setBounds(827, 339, 90, 30);

        btn_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kembaliMouseClicked(evt);
            }
        });
        getContentPane().add(btn_kembali);
        btn_kembali.setBounds(385, 153, 40, 40);

        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });
        getContentPane().add(btn_reset);
        btn_reset.setBounds(390, 340, 90, 30);

        sidebar.setMinimumSize(new java.awt.Dimension(277, 708));
        sidebar.setPreferredSize(new java.awt.Dimension(1089, 708));
        sidebar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        getContentPane().add(sidebar);
        sidebar.setBounds(0, 0, 277, 708);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/Tambah Data Paket.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1088, 708));
        jLabel1.setMinimumSize(new java.awt.Dimension(1088, 708));
        jLabel1.setPreferredSize(new java.awt.Dimension(1088, 708));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1088, 708);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        int price = txt_price.getText().isEmpty() ? 0 : Integer.parseInt(txt_price.getText());
        Package pkg = new Package(price, txt_name.getText());
        Set<ConstraintViolation<Package>> vols = ValidationUtil.validate(pkg);

        if(vols.size() < 1) {
            pkgRepo.add(pkg);
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan");

            new DataPaketView().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, ValidationUtil.getErrorsAsString(vols, "\n"));
        }
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void btn_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMouseClicked
        new DataPaketView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kembaliMouseClicked

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        txt_name.setText("");
        txt_price.setText("");
    }//GEN-LAST:event_btn_resetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahDataPaketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahDataPaketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahDataPaketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahDataPaketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahDataPaketView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_kembali;
    private javax.swing.JLabel btn_reset;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables
}
