/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polije.ppl.tailor.view.admin;

import java.util.HashMap;
import java.util.List;

import polije.ppl.tailor.data.AccountRole;
import polije.ppl.tailor.data.ComboItem;
import polije.ppl.tailor.entity.Account;
import polije.ppl.tailor.entity.Customer;
import polije.ppl.tailor.entity.Package;
import polije.ppl.tailor.entity.TransactionDetail;
import polije.ppl.tailor.repository.Repository;
import polije.ppl.tailor.repository.AccountRepository;
import polije.ppl.tailor.repository.CustomerRepository;
import polije.ppl.tailor.repository.PackageRepository;
import polije.ppl.tailor.view.util.SearchableComboBox;

/**
 *
 * @author muhai
 */
public class TambahTransaksiView extends javax.swing.JFrame {
    private Repository<Account> accRepo = new AccountRepository();
    private Repository<Customer> custRepo = new CustomerRepository();
    private Repository<Package> pkgRepo = new PackageRepository();

    /**
     * Creates new form TambahTransaksiView
     */
    public TambahTransaksiView() {
        fillComboBox();
        initComponents();
        initTransparent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_tanggal = new javax.swing.JTextField();
        totalharga = new javax.swing.JTextField();
        namapakaian = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        btn_kembali = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JLabel();
        btn_simpan2 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JLabel();
        btn_beranda = new javax.swing.JLabel();
        btn_pakey = new javax.swing.JLabel();
        btn_pelanggan = new javax.swing.JLabel();
        btn_transaksi = new javax.swing.JLabel();
        btn_penjahit = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JLabel();
        btn_panduan = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        catatan = new javax.swing.JTextArea();
        view = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1088, 708));
        setPreferredSize(new java.awt.Dimension(1088, 108));
        getContentPane().setLayout(null);

        txt_tanggal.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txt_tanggal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_tanggal.setBorder(null);
        txt_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tanggalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tanggal);
        txt_tanggal.setBounds(680, 220, 230, 30);

        totalharga.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        totalharga.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        totalharga.setBorder(null);
        totalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalhargaActionPerformed(evt);
            }
        });
        getContentPane().add(totalharga);
        totalharga.setBounds(730, 448, 180, 30);

        namapakaian.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        namapakaian.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        namapakaian.setBorder(null);
        namapakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapakaianActionPerformed(evt);
            }
        });
        getContentPane().add(namapakaian);
        namapakaian.setBounds(410, 307, 90, 30);

        jumlah.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jumlah.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jumlah.setBorder(null);
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(jumlah);
        jumlah.setBounds(630, 307, 90, 30);

        harga.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        harga.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        harga.setBorder(null);
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        getContentPane().add(harga);
        harga.setBounds(735, 307, 90, 30);

        btn_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kembaliMouseClicked(evt);
            }
        });
        getContentPane().add(btn_kembali);
        btn_kembali.setBounds(390, 85, 50, 40);

        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan);
        btn_simpan.setBounds(830, 300, 40, 40);
        getContentPane().add(btn_simpan2);
        btn_simpan2.setBounds(835, 650, 90, 40);

        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(873, 300, 40, 40);

        btn_beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_berandaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_beranda);
        btn_beranda.setBounds(37, 103, 200, 50);

        btn_pakey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pakeyMouseClicked(evt);
            }
        });
        getContentPane().add(btn_pakey);
        btn_pakey.setBounds(37, 175, 200, 50);

        btn_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pelangganMouseClicked(evt);
            }
        });
        getContentPane().add(btn_pelanggan);
        btn_pelanggan.setBounds(37, 245, 200, 50);

        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseClicked(evt);
            }
        });
        getContentPane().add(btn_transaksi);
        btn_transaksi.setBounds(37, 315, 200, 50);

        btn_penjahit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penjahitMouseClicked(evt);
            }
        });
        getContentPane().add(btn_penjahit);
        btn_penjahit.setBounds(37, 386, 200, 50);

        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_laporan);
        btn_laporan.setBounds(37, 457, 200, 50);

        btn_panduan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_panduanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_panduan);
        btn_panduan.setBounds(37, 527, 200, 50);

        btn_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_keluarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_keluar);
        btn_keluar.setBounds(40, 597, 200, 50);

        jTable1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(400, 340, 510, 80);

        catatan.setColumns(20);
        catatan.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        catatan.setRows(5);
        jScrollPane2.setViewportView(catatan);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(410, 505, 510, 120);

        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/Tambah Transaksi.png"))); // NOI18N
        getContentPane().add(view);
        view.setBounds(0, 0, 1090, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillComboBox() {
        ComboItem[] items;
        List<Customer> customers = custRepo.get();
        List<Package> packages = pkgRepo.get();
        List<Account> tailors = accRepo.get(new HashMap<>(){{
            put("role", AccountRole.tailor.toString());
        }});
        
        items = new ComboItem[customers.size()];
        for(int i = 0; i < customers.size(); i++) {
            Customer customer = customers.get(i);
            items[i] = new ComboItem(customer.getId(), customer.getFullname());
        }
        
        customerInput = new SearchableComboBox(items);
        customerInput.setFont(new java.awt.Font("Ubuntu", 0, 16));
        customerInput.setBorder(null);
        customerInput.setBounds(420, 156, 490, 30);
        
        items = new ComboItem[tailors.size()];
        for(int i = 0; i < tailors.size(); i++) {
            Account account = tailors.get(i);
            items[i] = new ComboItem(account.getId(), account.getFullname());
        }
        
        tailorInput = new SearchableComboBox(items);
        tailorInput.setFont(new java.awt.Font("Ubuntu", 0, 16));
        tailorInput.setBorder(null);
        tailorInput.setBounds(420, 223, 230, 30);
        
        items = new ComboItem[packages.size()];
        for(int i = 0; i < packages.size(); i++) {
            Package pkg = packages.get(i);
            items[i] = new ComboItem(pkg.getId(), pkg.getName());
        }
        
        packageInput = new SearchableComboBox(items);
        packageInput.setFont(new java.awt.Font("Ubuntu", 0, 16));
        packageInput.setBorder(null);
        packageInput.setBounds(520, 307, 90, 30);
        
        getContentPane().add(customerInput);
        getContentPane().add(tailorInput);
        getContentPane().add(packageInput);
    }
    
    private void initTransparent() {
        txt_tanggal.setOpaque(false);
        txt_tanggal.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        customerInput.setOpaque(false);
        customerInput.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        tailorInput.setOpaque(false);
        tailorInput.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        namapakaian.setOpaque(false);
        namapakaian.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        jumlah.setOpaque(false);
        jumlah.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        harga.setOpaque(false);
        harga.setBackground(new java.awt.Color(255, 255, 255, 0));
         
        totalharga.setOpaque(false);
        totalharga.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        packageInput.setOpaque(false);
        packageInput.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(null);
        
        catatan.setOpaque(false);
        catatan.setBackground(new java.awt.Color(255, 255, 255, 0));
    }
    
    private void txt_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggalActionPerformed

    private void totalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalhargaActionPerformed

    private void namapakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapakaianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapakaianActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked

    }//GEN-LAST:event_btn_simpanMouseClicked

    private void btn_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_kembaliMouseClicked

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_berandaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_berandaMouseClicked

    private void btn_pakeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pakeyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pakeyMouseClicked

    private void btn_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pelangganMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pelangganMouseClicked

    private void btn_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_transaksiMouseClicked

    private void btn_penjahitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjahitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_penjahitMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btn_panduanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panduanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_panduanMouseClicked

    private void btn_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_keluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahTransaksiView().setVisible(true);
            }
        });
    }
    
    private javax.swing.JComboBox customerInput;
    private javax.swing.JComboBox tailorInput;
    private javax.swing.JComboBox packageInput;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_beranda;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_keluar;
    private javax.swing.JLabel btn_kembali;
    private javax.swing.JLabel btn_laporan;
    private javax.swing.JLabel btn_pakey;
    private javax.swing.JLabel btn_panduan;
    private javax.swing.JLabel btn_pelanggan;
    private javax.swing.JLabel btn_penjahit;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel btn_simpan2;
    private javax.swing.JLabel btn_transaksi;
    private javax.swing.JTextArea catatan;
    private javax.swing.JTextField harga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField namapakaian;
    private javax.swing.JTextField totalharga;
    private javax.swing.JTextField txt_tanggal;
    private javax.swing.JLabel view;
    // End of variables declaration//GEN-END:variables
}
