/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polije.ppl.tailor.view.admin;

/**
 *
 * @author muhai
 */
public class TambahDataPenjahitView extends javax.swing.JFrame {

    /**
     * Creates new form TambahDataPenjahitView
     */
    public TambahDataPenjahitView() {
        initComponents();
        txt_namapenjahit.setOpaque(false);
        txt_namapenjahit.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        txt_username.setOpaque(false);
        txt_username.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        txt_email.setOpaque(false);
        txt_email.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        pass.setOpaque(false);
        pass.setBackground(new java.awt.Color(255, 255, 255, 0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_email = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_namapenjahit = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        btn_simpan = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JLabel();
        btn_beranda = new javax.swing.JLabel();
        btn_paket = new javax.swing.JLabel();
        btn_pelanggan = new javax.swing.JLabel();
        btn_transaksi = new javax.swing.JLabel();
        btn_penjahit = new javax.swing.JLabel();
        btn_panduan = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JLabel();
        view = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1088, 708));
        setPreferredSize(new java.awt.Dimension(1088, 708));
        getContentPane().setLayout(null);

        txt_email.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txt_email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_email.setBorder(null);
        getContentPane().add(txt_email);
        txt_email.setBounds(670, 330, 230, 40);

        txt_username.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txt_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_username.setBorder(null);
        getContentPane().add(txt_username);
        txt_username.setBounds(400, 332, 230, 40);

        txt_namapenjahit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txt_namapenjahit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_namapenjahit.setBorder(null);
        getContentPane().add(txt_namapenjahit);
        txt_namapenjahit.setBounds(400, 260, 500, 40);

        pass.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        pass.setBorder(null);
        getContentPane().add(pass);
        pass.setBounds(400, 402, 490, 40);

        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan);
        btn_simpan.setBounds(810, 460, 100, 30);

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/TombolHapus.png"))); // NOI18N
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(387, 456, 90, 40);

        btn_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kembaliMouseClicked(evt);
            }
        });
        getContentPane().add(btn_kembali);
        btn_kembali.setBounds(370, 190, 50, 40);

        btn_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_keluarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_keluar);
        btn_keluar.setBounds(37, 595, 200, 50);

        btn_beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_berandaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_beranda);
        btn_beranda.setBounds(37, 105, 200, 50);

        btn_paket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_paketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_paketMouseEntered(evt);
            }
        });
        getContentPane().add(btn_paket);
        btn_paket.setBounds(37, 175, 200, 50);

        btn_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pelangganMouseClicked(evt);
            }
        });
        getContentPane().add(btn_pelanggan);
        btn_pelanggan.setBounds(37, 245, 200, 50);

        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseClicked(evt);
            }
        });
        getContentPane().add(btn_transaksi);
        btn_transaksi.setBounds(37, 317, 200, 50);

        btn_penjahit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penjahitMouseClicked(evt);
            }
        });
        getContentPane().add(btn_penjahit);
        btn_penjahit.setBounds(37, 385, 200, 50);

        btn_panduan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_panduanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_panduan);
        btn_panduan.setBounds(37, 525, 200, 50);

        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_laporan);
        btn_laporan.setBounds(37, 457, 200, 50);

        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pages/Tambah Penjahit.png"))); // NOI18N
        getContentPane().add(view);
        view.setBounds(0, 0, 1089, 708);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_kembaliMouseClicked

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_keluarMouseClicked

    private void btn_berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_berandaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_berandaMouseClicked

    private void btn_paketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_paketMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_paketMouseEntered

    private void btn_paketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_paketMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_paketMouseClicked

    private void btn_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pelangganMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pelangganMouseClicked

    private void btn_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_transaksiMouseClicked

    private void btn_penjahitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjahitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_penjahitMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btn_panduanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panduanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_panduanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahDataPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahDataPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahDataPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahDataPenjahitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahDataPenjahitView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_beranda;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_keluar;
    private javax.swing.JLabel btn_kembali;
    private javax.swing.JLabel btn_laporan;
    private javax.swing.JLabel btn_paket;
    private javax.swing.JLabel btn_panduan;
    private javax.swing.JLabel btn_pelanggan;
    private javax.swing.JLabel btn_penjahit;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel btn_transaksi;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_namapenjahit;
    private javax.swing.JTextField txt_username;
    private javax.swing.JLabel view;
    // End of variables declaration//GEN-END:variables
}
